# https://taskfile.dev

version: '3'

vars:
  CURRENT_DIR:
    sh: pwd
  SUFFIX: '{{if eq OS "windows"}}.exe{{end}}'

tasks:
  default:
    cmds:
      - task --list-all

  lint:
    cmds:
      - docker run --rm -v {{toSlash .CURRENT_DIR}}:/app -w /app golangci/golangci-lint:v2.6.2 golangci-lint run -v --timeout 5m

  upgrade-libraries:
    cmds:
      - go get go@latest
      - go get -u ./...
      - go fmt ./...
      - go mod tidy
      - go mod verify

  tidy:
    cmds:
      - go fmt ./...
      - go mod tidy -v

  audit:
    cmds:
      - go vet ./...
      - go run honnef.co/go/tools/cmd/staticcheck@latest -checks=all,-ST1000,-U1000 ./...
      - go mod verify

  build:
    cmds:
      - go build -ldflags='-s' -o=./bin/api{{.SUFFIX}} ./cmd/api

  run:
    deps: [build]
    cmds:
      - ./bin/api{{.SUFFIX}}
